using Test
using EegFun

println("Running EegFun.jl Test Suite")
println("="^40)

@testset "EegFun" begin

    include("tests/apply.jl")
    include("tests/artifact_detection.jl")
    include("tests/baseline.jl")
    include("tests/batch_utils.jl")
    include("tests/channel_average.jl")
    include("tests/channel_difference.jl")
    include("tests/channel_metrics.jl")
    include("tests/channel_repair.jl")
    include("tests/channel_summary.jl")
    include("tests/condition_combine.jl")
    include("tests/condition_difference.jl")
    include("tests/config.jl")
    include("tests/data.jl")
    include("tests/epochs.jl")
    include("tests/erp_measurements.jl")
    include("tests/files.jl")
    include("tests/filter.jl")
    include("tests/gfp.jl")
    include("tests/grand_average.jl")
    include("tests/ica.jl")
    include("tests/jackknife_average.jl")
    include("tests/layout.jl")
    include("tests/layout_system.jl")
    include("tests/logging.jl")
    include("tests/lrp.jl")
    include("tests/mirror.jl")
    include("tests/misc.jl")
    include("tests/plot_channel_summary.jl")
    include("tests/plot_layout.jl")
    include("tests/plot_misc.jl")
    include("tests/plot_triggers.jl")
    include("tests/print.jl")
    include("tests/realign.jl")
    include("tests/rereference.jl")
    include("tests/resample.jl")
    include("tests/subset.jl")
    include("tests/triggers.jl")
    include("tests/types.jl")
    include("tests/utils.jl")

end

println("\nAll tests completed!")
