# Public API declarations
# The `public` keyword marks names as part of the public API without
# exporting them into the user's namespace (no namespace clash risk).
# Internal functions are prefixed with _ and are not listed here.
# Internal types (state machines, GUI state, buffers) are NOT listed here
# but remain accessible via EegFun.TypeName if needed.
# Alphabetically sorted within each category.

# =====================
# Types — User-facing data, result, and config types
# =====================
public AnalysisData
public AnalysisSettings
public AnalyticResult
public ArtifactComponents
public ArtifactInfo
public BaselineInfo
public BatchConfig
public BatchResult
public ChannelRepairInfo
public Cluster
public ClusterInfo
public Clusters
public Component
public ContinuousData
public ContinuousRepairInfo
public DecodedData
public DecodingParameters
public DecodingStatisticsResult
public EegConfig
public EegData
public EegFunData
public EogConfig
public EpochData
public EpochInfo
public EpochRejectionInfo
public EpochRepairInfo
public ErpData
public ErpMeasurementsResult
public ExtraChannelInfo
public FilterConfig
public FilterInfo
public FilterSection
public IcaConfig
public IcaPrms
public InfoIca
public Interval
public Layout
public MultiDataFrameEeg
public Neighbours
public NoiseCeiling
public PermutationDistribution
public PermutationResult
public PreprocessConfig
public Rejection
public SingleDataFrameEeg
public SpectrumData
public StatisticalData
public StatsResult
public TemporalCluster
public TestInfo
public TFAnalysisData
public TFAnalyticResult
public TFCluster
public TFClusterPermutationResult
public TFClusters
public TFStatisticalData
public TFStatsResult
public TimeFreqData
public TimeFreqEpochData
public TriggerInfo
public TTestResult
public ZScoreRejectionInfo

# =====================
# Data access and utilities
# =====================
public all_data
public channel_data
public channel_labels
public channels
public channels_not
public components
public components_not
public conditions
public conditions_not
public create_eegfun_data
public extra_data
public file_name
public head
public meta_data
public n_values
public epochs
public epochs_not
public participants
public participants_not
public sample_rate
public samples
public samples_and
public samples_and_not
public samples_not
public samples_or
public samples_or_not
public section
public subset
public subset_bad_data
public tail
public times
public to_data_frame
public viewer

# =====================
# I/O
# =====================
public download_eegfun_datasets
public find_file
public get_files
public read_all_data
public read_config
public read_fieldtrip_csv
public read_data
public read_eeglab
public read_fieldtrip
public read_layout
public read_raw_data
public read_xdf

# =====================
# Layout
# =====================
public average_number_of_neighbours
public check_channel_neighbors
public create_custom_layout
public create_layout
public get_neighbours_xy!
public get_neighbours_xyz!
public has_valid_coordinates
public polar_to_cartesian_xy!
public polar_to_cartesian_xyz!
public print_layout_neighbours
public subset_layout
public subset_layout!
public validate_layout

# =====================
# Preprocessing
# =====================
public average_epochs
public baseline
public baseline!
public cleanline
public cleanline!
public create_highpass_filter
public create_lowpass_filter
public detrend
public epochs_count
public epochs_table
public extract_epochs
public find_times
public get_filter_characteristics
public highpass_filter
public highpass_filter!
public log_epochs_table

public lowpass_filter
public lowpass_filter!
public mark_epoch_intervals!
public mirror
public mirror!
public print_filter_characteristics
public reject_epochs
public reject_epochs!
public rereference
public rereference!
public resample
public resample!
public unmirror
public unmirror!

# =====================
# Channel and condition operations
# =====================
public channel_average
public channel_average!
public channel_delete
public channel_delete!
public channel_difference
public channel_difference!
public channel_joint_probability
public channel_repairable
public channel_repairable!
public channel_summary
public condition_average
public condition_combine
public condition_difference
public condition_parse_epoch
public correlation_matrix
public correlation_matrix_dual_selection
public correlation_matrix_eog
public rename_channel
public rename_channel!

# =====================
# RSA (Representational Similarity Analysis)
# =====================
public add_noise_ceiling!
public compare_models
public compute_noise_ceiling
public create_model_rdms
public create_rdm_from_categorical
public create_rdm_from_distances
public create_rdm_from_matrix
public create_rdm_from_reaction_times
public create_rdm_from_similarity_ratings
public create_rdm_from_timeseries
public create_rdm_from_vectors
public create_temporal_model_rdms
public normalize_rdm
public rsa
public rsa_crossvalidated

# =====================
# Artifact detection and repair
# =====================
public compare_rejections
public consecutive
public create_continuous_repair_info
public create_epoch_repair_info
public detect_bad_epochs_automatic
public detect_bad_epochs_interactive
public get_rejected_epochs
public identify_bad_channels
public is_extreme_value
public is_extreme_value!
public is_step_value
public is_step_value!
public n_extreme_value
public n_step_value
public repair_artifacts
public repair_artifacts!
public repair_artifacts_neighbor!
public repair_artifacts_spherical_spline!
public repair_channels
public summarize_electrode_repairs
public unique_rejections
public compute_csd
public compute_csd!

# =====================
# ICA
# =====================
public calculate_eog_channels!
public combine_artifact_components
public detect_eog_onsets!
public detect_eog_onsets!
public get_all_ica_components
public get_eog_channels
public get_selected_components
public identify_components
public identify_ecg_components
public identify_eog_components
public identify_line_noise_components
public identify_spatial_kurtosis_components
public infomax_extended_ica
public infomax_ica
public partition_channels_by_eog_correlation
public subtract_ica_components
public add_ica_components
public run_ica
public summarize_ica_components

# =====================
# ERP analysis
# =====================
public calculate_trigger_interval
public calculate_trigger_interval!
public erp_measurements
public erp_measurements!
public gfp
public gfp_and_dissimilarity
public global_dissimilarity
public grand_average
public jackknife_average
public lrp
public realign
public realign!

# =====================
# Statistics
# =====================
public analytic_test
public permutation_test
public prepare_stats

# =====================
# Time-frequency
# =====================
public freq_spectrum
public tf_baseline
public tf_baseline!
public tf_morlet
public tf_multitaper
public tf_stft

# =====================
# Decoding / MVPA
# =====================
public decode_libsvm
public libsvm_classifier
public prepare_decoding
public resample_temporal_data
public test_against_chance
public test_against_chance_cluster

# =====================
# Triggers
# =====================
public allcomb
public search_sequence
public trigger_count
public trigger_info

# =====================
# Pipelines and config
# =====================
public apply_analysis_settings
public apply_analysis_settings!
public generate_config_template
public read_bids
public export_bids
public generate_pipeline_template
public preprocess

public print_config
public show_parameter_info

# =====================
# Plotting
# =====================
public plot_artifact_components
public plot_artifact_detection
public plot_artifact_rejection
public plot_artifact_repair
public plot_channel_spectrum
public plot_channel_summary
public plot_channel_summary!
public plot_confusion_matrix
public plot_correlation_heatmap
public plot_correlation_heatmap!
public plot_databrowser
public plot_decoding
public plot_ecg_component_features
public plot_eog_component_features
public plot_epochs
public plot_erp
public plot_erp!
public plot_erp_filter_gui
public plot_erp_image
public plot_erp_measurement_gui
public plot_erp_measurements
public plot_erp_stats
public plot_stat_heatmap
public plot_filter_response
public plot_gfp
public plot_gui
public plot_ica_component_activation
public plot_ica_component_spectrum
public plot_joint_probability
public plot_joint_probability!
public plot_layout
public plot_layout!
public plot_layout_2d
public plot_layout_2d!
public plot_layout_3d
public plot_layout_3d!
public plot_line_noise_components
public plot_spatial_kurtosis_components
public plot_tf_stats
public plot_tf
public plot_topography
public plot_topography_3d
public plot_topography!
public plot_topography_stats
public plot_trigger_overview
public plot_trigger_timing

# =====================
# Plot helpers (user-facing selection helpers)
# =====================
public add_topo_rois!
public get_selected_channels
public get_selected_conditions
public get_selected_epochs
public get_selected_samples

# =====================
# Logging
# =====================
public close_logging
public setup_logging

# =====================
# Demos
# =====================
public generate_signal
public signal_example_composition
public signal_example_convolution
public signal_example_dotproduct
public signal_example_ica_mixture
public signal_example_ica_separation
public signal_example_ica_geometry
public signal_example_ica_clt
public signal_example_ica_sphering
public signal_example_ica_optimization
public signal_example_sampling
public signal_example_tf
public signal_to_data
public simulate_erp
public signal_example_decoding

# =====================
# Misc
# =====================
public example_path
public version_info
public get_package_version
