# Public API declarations
# The `public` keyword marks names as part of the public API without
# exporting them into the user's namespace (no namespace clash risk).
# Internal functions are prefixed with _ and are not listed here.
# Alphabetically sorted within each category.

# =====================
# Types
# =====================
public AbstractDataState
public AnalysisData
public AnalysisSettings
public AnalyticResult
public ArtifactComponents
public ArtifactInfo
public BaselineInfo
public BatchConfig
public BatchResult
public ChannelRepairInfo
public ChannelState
public Cluster
public ClusterInfo
public Clusters
public Component
public ConfigParameter
public ContinuousData
public ContinuousDataState
public ContinuousRepairInfo
public DataBrowserState
public DecodedData
public DecodingParameters
public DecodingStatisticsResult
public EegConfig
public EegData
public EegFunData
public EogConfig
public EpochData
public EpochedDataState
public EpochInfo
public EpochRejectionInfo
public EpochRejectionState
public EpochRepairInfo
public ErpData
public ErpMeasurementsResult
public ExtraChannelInfo
public FilterConfig
public FilterInfo
public FilterSection
public FilterState
public IcaComponentState
public IcaConfig
public IcaPrms
public InfoIca
public Interval
public Layout
public LoggingState
public Marker
public Masks
public MultiDataFrameEeg
public Neighbours
public NoiseCeiling
public PermutationDistribution
public PermutationResult
public PipelineTemplateOptions
public PlotHelpInfo
public PlotLayout
public PreprocessConfig
public Rejection
public RsaData
public SelectionState
public SharedSelectionState
public SingleDataFrameEeg
public SpectrumData
public StatisticalData
public StatMatrix
public StatsResult
public TemporalCluster
public TestInfo
public TFAnalysisData
public TFAnalyticResult
public TFCluster
public TFClusterPermutationResult
public TFClusters
public TFMasks
public TFStatisticalData
public TFStatMatrix
public TFStatsResult
public TimeFreqData
public TimeFreqEpochData
public ToggleConfig
public TopoSelectionState
public TriggerInfo
public TTestResult
public UIStyle
public ViewState
public WorkArrays
public ZScoreRejectionInfo

# =====================
# Data access and utilities
# =====================
public all_data
public channel_data
public channel_labels
public channels
public conditions
public extra_data
public file_name
public group_by_condition
public head
public meta_data
public n_values
public participants
public section
public subset
public subset_bad_data
public tail
public times
public to_data_frame
public viewer

# =====================
# I/O
# =====================
public check_files_exist
public find_file
public get_files
public read_all_data
public read_config
public read_csv
public read_data
public read_eeglab
public read_fieldtrip
public read_layout
public read_raw_data

# =====================
# Layout
# =====================
public average_number_of_neighbours
public check_channel_neighbors
public clear_neighbours
public create_custom_layout
public create_layout
public get_neighbours_xy
public get_neighbours_xyz
public has_valid_coordinates
public polar_to_cartesian_xy
public polar_to_cartesian_xyz
public print_layout_neighbours
public subset_layout
public subset_layout!
public validate_layout

# =====================
# Preprocessing
# =====================
public average_epochs
public baseline
public baseline!
public create_highpass_filter
public create_lowpass_filter
public detrend
public epochs_table
public extract_epochs
public find_times
public get_filter_characteristics
public highpass_filter
public highpass_filter!
public log_epochs_table
public lowpass_filter
public lowpass_filter!
public mark_epoch_intervals
public mark_epoch_intervals!
public mirror
public mirror!
public print_filter_characteristics
public reject_epochs
public reject_epochs!
public rereference
public rereference!
public resample
public resample!
public unmirror
public unmirror!

# =====================
# Channel and condition operations
# =====================
public channel_average
public channel_average!
public channel_delete
public channel_delete!
public channel_difference
public channel_difference!
public channel_joint_probability
public channel_repairable
public channel_repairable!
public channel_summary
public condition_average
public condition_combine
public condition_difference
public condition_parse_epoch
public correlation_matrix
public correlation_matrix_dual_selection
public correlation_matrix_eog
public rename_channel
public rename_channel!

# =====================
# Artifact detection and repair
# =====================
public compare_rejections
public consecutive
public create_continuous_repair_info
public create_epoch_repair_info
public detect_bad_epochs_automatic
public detect_bad_epochs_interactive
public get_rejected_epochs
public identify_bad_channels
public is_extreme_value
public is_extreme_value!
public is_step_value
public is_step_value!
public n_extreme_value
public n_step_value
public repair_artifacts
public repair_artifacts!
public repair_artifacts_neighbor
public repair_artifacts_neighbor!
public repair_artifacts_spherical_spline
public repair_artifacts_spherical_spline!
public repair_channels
public repair_channels_neighbor
public repair_channels_per_epoch
public repair_channels_spherical
public summarize_electrode_repairs
public unique_rejections

# =====================
# ICA
# =====================
public calculate_eog_channels
public calculate_eog_channels!
public combine_artifact_components
public detect_eog_onsets
public detect_eog_onsets!
public detect_eog_signals
public detect_eog_signals!
public get_all_ica_components
public get_eog_channels
public get_selected_components
public identify_components
public identify_ecg_components
public identify_eog_components
public identify_line_noise_components
public identify_spatial_kurtosis_components
public infomax_extended_ica
public infomax_ica
public partition_channels_by_eog_correlation
public remove_ica_components
public restore_ica_components
public run_ica
public summarize_ica_components

# =====================
# ERP analysis
# =====================
public erp_measurements
public erp_measurements!
public gfp
public gfp_and_dissimilarity
public global_dissimilarity
public grand_average
public jackknife_average
public lrp
public realign
public realign!

# =====================
# Statistics
# =====================
public analytic_test
public compute_probability
public permutation_test
public prepare_stats

# =====================
# Time-frequency
# =====================
public freq_spectrum
public tf_baseline
public tf_baseline!
public tf_morlet
public tf_multitaper
public tf_stft

# =====================
# Decoding / MVPA
# =====================
public create_work_arrays
public decode_libsvm
public libsvm_classifier
public prepare_decoding
public resample_temporal_data
public test_against_chance
public test_against_chance_cluster

# =====================
# RSA
# =====================
public add_noise_ceiling
public add_noise_ceiling!
public compare_models
public compute_noise_ceiling
public create_model_rdms
public create_rdm_from_categorical
public create_rdm_from_distances
public create_rdm_from_matrix
public create_rdm_from_reaction_times
public create_rdm_from_similarity_ratings
public create_rdm_from_timeseries
public create_rdm_from_vectors
public create_temporal_model_rdms
public normalize_rdm
public rsa
public rsa_crossvalidated

# =====================
# Triggers
# =====================
public search_sequence
public trigger_count

# =====================
# Pipelines and config
# =====================
public apply_analysis_settings
public apply_analysis_settings!
public generate_config_template
public generate_pipeline_template
public preprocess_v1
public preprocess_v2
public print_config
public show_parameter_info

# =====================
# Plotting
# =====================
public plot_artifact_components
public plot_artifact_detection
public plot_artifact_rejection
public plot_artifact_repair
public plot_channel_spectrum
public plot_channel_summary
public plot_channel_summary!
public plot_confusion_matrix
public plot_correlation_heatmap
public plot_correlation_heatmap!
public plot_databrowser
public plot_decoding
public plot_ecg_component_features
public plot_eog_component_features
public plot_epochs
public plot_erp
public plot_erp!
public plot_erp_filter_gui
public plot_erp_image
public plot_erp_measurement_gui
public plot_erp_measurements
public plot_erp_stats
public plot_filter_response
public plot_frequency_spectrum
public plot_gfp
public plot_gui
public plot_ica_component_activation
public plot_ica_component_spectrum
public plot_joint_probability
public plot_joint_probability!
public plot_layout_2d
public plot_layout_2d!
public plot_layout_3d
public plot_layout_3d!
public plot_line_noise_components
public plot_model_correlations
public plot_power_spectrum
public plot_rdm_heatmap
public plot_rdm_timecourse
public plot_rsa
public plot_spatial_kurtosis_components
public plot_tf_stats
public plot_tf
public plot_topography
public plot_topography!
public plot_topo_stats
public plot_trigger_overview
public plot_trigger_timing

# =====================
# Plot helpers
# =====================
public add_topo_rois
public add_topo_rois!
public add_zscore_columns
public combine_boolean_columns
public get_plot_help_info
public get_selected_channels
public get_selected_conditions
public get_selected_epochs
public get_selected_samples
public print_plot_help
public show_plot_help

# =====================
# Logging
# =====================
public close_logging
public setup_logging

# =====================
# Data creation (testing and demos)
# =====================
public create_batch_test_erp_data
public create_eegfun_data
public create_test_continuous_data
public create_test_continuous_data_empty_triggers
public create_test_continuous_data_with_artifacts
public create_test_continuous_data_with_triggers
public create_test_epoch_data
public create_test_epoch_data_vector
public create_test_epoch_data_with_artifacts
public create_test_epoch_data_with_rt
public create_test_erp_data
public create_test_layout
public create_test_lrp_data
public create_test_summary_data
public create_test_summary_data_with_epochs
public create_test_tf_data

# =====================
# Demos
# =====================
public generate_signal
public signal_example_1
public signal_example_2
public signal_to_data
public simulate_erp

# =====================
# Misc
# =====================
public EegFun_version_info
public get_package_version
